### ISSUE TITLE
OS X check for updates looks for non-existent file

### ISSUE THREAD

**Issue by casusbelli** [OttoDIY/blockly#141]
Seems the file location is wrong or there's no anonymous access to that?

Error message:
Error: Cannot find latest-mac.yml in the latest release artifacts (https://github.com/OttoDIY/blockly/releases/download/v1.4.4/latest-mac.yml): HttpError: 404 
"method: undefined url: https://github.com/OttoDIY/blockly/releases/download/v1.4.4/latest-mac.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
"cache-control": [
"no-cache"
],
"content-encoding": [
"gzip"
],
"content-security-policy": [
"default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'"
],
"content-type": [
"text/plain; charset=utf-8"
],
"date": [
"Sat, 01 Jan 2022 14:08:44 GMT"
],
"expect-ct": [
"max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\""
],
"permissions-policy": [
"interest-cohort=()"
],
"referrer-policy": [
"no-referrer-when-downgrade"
],
"server": [
"GitHub.com"
],
"status": [
"404"
],
"strict-transport-security": [
"max-age=31536000; includeSubdomains; preload"
],
"vary": [
"X-PJAX, X-PJAX-Container, Accept-Encoding, Accept, X-Requested-With"
],
"x-content-type-options": [
"nosniff"
],
"x-frame-options": [
"deny"
],
"x-github-request-id": [
"E481:1417:397B0ED:3CEC612:61D0606C"
],
"x-xss-protection": [
"0"
]
}
at createHttpError (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/builder-util-runtime/src/httpExecutor.ts:30:10)
at ElectronHttpExecutor.handleResponse (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/builder-util-runtime/src/httpExecutor.ts:129:14)
at ClientRequest.request.createRequest.response (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/builder-util-runtime/src/httpExecutor.ts:85:16)
at ClientRequest.emit (events.js:182:13)
at URLRequest.ClientRequest.urlRequest.on (/Applications/OttoBlockly.app/Contents/Resources/electron.asar/browser/api/net.js:207:12)
at URLRequest.emit (events.js:182:13)
From previous event:
at GitHubProvider.getLatestVersion (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/providers/GitHubProvider.ts:39:25)
at /Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:347:26
at Generator.next (<anonymous>)
at runCallback (timers.js:694:18)
at tryOnImmediate (timers.js:665:5)
at processImmediate (timers.js:647:5)
From previous event:
at MacUpdater.getUpdateInfoAndProvider (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:336:43)
at /Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:363:31
at Generator.next (<anonymous>)
From previous event:
at MacUpdater.doCheckForUpdates (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:360:34)
at MacUpdater.checkForUpdates (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:220:35)
at EventEmitter.<anonymous> (/Applications/OttoBlockly.app/Contents/Resources/app/electronApp.js:76:14)
at EventEmitter.emit (events.js:182:13)
at WebContents.<anonymous> (/Applications/OttoBlockly.app/Contents/Resources/electron.asar/browser/api/web-contents.js:346:13)
at WebContents.emit (events.js:182:13)
at createHttpError (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/builder-util-runtime/src/httpExecutor.ts:30:10)
at ElectronHttpExecutor.handleResponse (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/builder-util-runtime/src/httpExecutor.ts:129:14)
at ClientRequest.request.createRequest.response (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/builder-util-runtime/src/httpExecutor.ts:85:16)
at ClientRequest.emit (events.js:182:13)
at URLRequest.ClientRequest.urlRequest.on (/Applications/OttoBlockly.app/Contents/Resources/electron.asar/browser/api/net.js:207:12)
at URLRequest.emit (events.js:182:13)
at GitHubProvider.getLatestVersion (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/providers/GitHubProvider.ts:39:25)
at /Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:347:26
at Generator.next (<anonymous>)
at runCallback (timers.js:694:18)
at tryOnImmediate (timers.js:665:5)
at processImmediate (timers.js:647:5)
at MacUpdater.getUpdateInfoAndProvider (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:336:43)
at /Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:363:31
at Generator.next (<anonymous>)
at MacUpdater.doCheckForUpdates (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:360:34)
at MacUpdater.checkForUpdates (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:220:35)
at EventEmitter.<anonymous> (/Applications/OttoBlockly.app/Contents/Resources/app/electronApp.js:76:14)
at EventEmitter.emit (events.js:182:13)
at WebContents.<anonymous> (/Applications/OttoBlockly.app/Contents/Resources/electron.asar/browser/api/web-contents.js:346:13)
at WebContents.emit (events.js:182:13)
at newError (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/builder-util-runtime/src/index.ts:29:17)
at /Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/providers/GitHubProvider.ts:82:15
at Generator.throw (<anonymous>)
From previous event:
at GitHubProvider.getLatestVersion (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/providers/GitHubProvider.ts:39:25)
at /Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:347:26
at Generator.next (<anonymous>)
at runCallback (timers.js:694:18)
at tryOnImmediate (timers.js:665:5)
at processImmediate (timers.js:647:5)
From previous event:
at MacUpdater.getUpdateInfoAndProvider (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:336:43)
at /Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:363:31
at Generator.next (<anonymous>)
From previous event:
at MacUpdater.doCheckForUpdates (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:360:34)
at MacUpdater.checkForUpdates (/Applications/OttoBlockly.app/Contents/Resources/app/node_modules/electron-updater/src/AppUpdater.ts:220:35)
at EventEmitter.<anonymous> (/Applications/OttoBlockly.app/Contents/Resources/app/electronApp.js:76:14)
at EventEmitter.emit (events.js:182:13)
at WebContents.<anonymous> (/Applications/OttoBlockly.app/Contents/Resources/electron.asar/browser/api/web-contents.js:346:13)
at WebContents.emit (events.js:182:13)

**Comment by takujikawata-pr** [comment]
Thanks for the report. I reproduced it and the issue is fixed by the 1.4.5 release.
